language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
services:
  - memcached
# command to run tests
script: 
  - python3 tests.py || python tests.py
  - pytest --flake8
